import Head from "next/head";

type LayoutProps = {
  title?: string;
  description?: string;
  children: React.ReactNode;
};

function Layout({
  title = "Todo App",
  description = "Generated by create-t3-app",
  children,
}: LayoutProps) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gray-800">
        <section className="container flex flex-col gap-4 px-4 py-4 md:mx-auto md:max-w-screen-md">
          {children}
        </section>
      </main>
    </>
  );
}

export default Layout;
